declare module '*.css';
declare module '@/components/ui/button';
declare module '@/components/ui/input';
declare module '@/components/ui/label'
declare module '@/components/ui/alert';
declare module '@/lib/api'
declare module '@/lib/auth';
declare module 'lucide-react';
declare module 'react';
declare module 'next';
declare module '@/components/ui/card'
declare module '@/components/ui/select'
declare module '@/components/ui/textarea'
declare module '@/components/ui/tabs'
declare module '@/components/icons/qr-code-scan'
declare module '@/components/ui/badge'
declare module '@/components/ui/dialog'
declare module '@/components/ui/popover'
declare module '@/components/ui/use-toast'
declare module '@/components/providers/theme-provider'
declare module 'framer-motion'
declare module 'radix-ui'
declare module 'class-variance-authority'
declare module 'next/image'
declare module 'next/link'
declare module 'next/navigation'
declare module 'next-themes'
declare module '@/components/ui/sidebar'
declare module '@/components/ui/avatar'
declare module '@/components/ui/separator'
declare module '@/lib/store'
declare module '@/lib/utils'
declare module '@/components/ui/sidebar'
declare module '@/components/ui/avatar'
declare module '@/components/ui/separator'
